name: Build and Update Documentation

on:
  push:
    branches: [master, develop]
    paths:
      - 'src/**'
      - 'angular/projects/lib/**'
      - 'typedoc*.json'
      - 'package.json'
      - 'scripts/generate-docs.js'
      - 'scripts/reorder-*.js'
  pull_request:
    branches: [master, develop]
    paths:
      - 'src/**'
      - 'angular/projects/lib/**'
      - 'typedoc*.json'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    if: github.repository == 'gridstack/gridstack.js'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Install Angular dependencies
      run: |
        cd angular
        yarn install --frozen-lockfile

    - name: Build TypeScript
      run: |
        yarn t

    - name: Generate documentation
      run: |
        yarn doc:all

    - name: Configure Git
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit updated documentation
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        # Check if there are changes to the documentation
        if git diff --quiet doc/ angular/doc/; then
          echo "No documentation changes to commit"
          exit 0
        fi
        
        # Add documentation changes
        git add doc/ angular/doc/
        
        # Create commit message
        COMMIT_MSG="📚 Auto-update documentation

Generated from latest source code changes
- Updated TypeDoc HTML documentation
- Updated API documentation

Source: ${{ github.sha }}"
        
        # Commit changes
        git commit -m "$COMMIT_MSG"
        git push origin master
        
        echo "✅ Documentation updated and committed to master!"

    - name: Upload documentation artifacts
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: documentation-preview
        path: |
          doc/html/
          angular/doc/html/
        retention-days: 7
